FROM golang:1.15

RUN mkdir /go/src/kimo
COPY go.mod go.sum /go/src/pas/

COPY . /go/src/pas
RUN cd /go/src/pas && go install

ADD config.toml /etc/pas.toml

ENTRYPOINT ["pas", "-config", "/etc/pas.toml"]
